version: '3'
services:
  oggora:
    container_name: oggora
    build: .
    image: oggora:latest
    command: sh -c "/tmp/init.sh"
    ports:
      - 8888:8888
    volumes:
      - ./object_detection:/tf/object_detection
    networks:
      default:
networks:
  default: